STATIONS = "stations"

STATION_CODE = "station_code"
INDICATOR = "indicator"
AVERAGE_TIME = "avg_time"
UNIT = "unit"
POSITION_CODE = "position_code"
VALUE = "value"
TIMESTAMP = "timestamp"

METADATA_STATION_CODE = "Kod stacji"
METADATA_STATION_NAME = "Nazwa stacji"
METADATA_ADDRESS = "Adres"
METADATA_CITY = "Miejscowość"
METADATA_VOIVODESHIP = "Województwo"
METADATA_LATITUDE = "WGS84 φ N"
METADATA_LONGITUDE = "WGS84 λ E"
METADATA_OPEN_DATE = "Data uruchomienia"
METADATA_CLOSE_DATE = "Data zamknięcia"
METADATA_STATION_KIND = "Rodzaj stacji"
